// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PovarCRM.Models;

#nullable disable

namespace PovarCRM.Migrations
{
    [DbContext(typeof(PovarDbContext))]
    [Migration("20250917151328_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PovarCRM.Models.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("money");

                    b.Property<int?>("DishTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Naming")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id")
                        .HasName("PK__Dish__3214EC073FCC58D9");

                    b.HasIndex("DishTypeId");

                    b.HasIndex(new[] { "Naming" }, "UQ__Dish__EF1B1C3A7896333B")
                        .IsUnique();

                    b.ToTable("Dish", (string)null);
                });

            modelBuilder.Entity("PovarCRM.Models.DishProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("money");

                    b.Property<string>("Naming")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__DishProd__3214EC0793517D24");

                    b.HasIndex("UnitId");

                    b.HasIndex(new[] { "Naming" }, "UQ__DishProd__EF1B1C3AB945F017")
                        .IsUnique();

                    b.ToTable("DishProduct", (string)null);
                });

            modelBuilder.Entity("PovarCRM.Models.DishType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naming")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__DishType__3214EC070FA47347");

                    b.HasIndex(new[] { "Naming" }, "UQ__DishType__EF1B1C3ABD2469FD")
                        .IsUnique();

                    b.ToTable("DishType", (string)null);
                });

            modelBuilder.Entity("PovarCRM.Models.Item", b =>
                {
                    b.Property<int>("OrderCheckId")
                        .HasColumnType("int");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("DishCount")
                        .HasColumnType("int");

                    b.HasKey("OrderCheckId", "DishId")
                        .HasName("PK_consist_OrderCheckId_DishId");

                    b.HasIndex("DishId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("PovarCRM.Models.OrderCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Total")
                        .HasColumnType("money");

                    b.HasKey("Id")
                        .HasName("PK__OrderChe__3214EC07DDCE8732");

                    b.ToTable("OrderCheck", (string)null);
                });

            modelBuilder.Entity("PovarCRM.Models.Recipe", b =>
                {
                    b.Property<int>("DishProductId")
                        .HasColumnType("int");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<float>("CountOfUnits")
                        .HasColumnType("real");

                    b.HasKey("DishProductId", "DishId")
                        .HasName("PK_consist_DishProductId_DishId");

                    b.HasIndex(new[] { "DishId", "DishProductId" }, "UQ_Dish_Unit")
                        .IsUnique();

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("PovarCRM.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naming")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__Unit__3214EC07D9854487");

                    b.HasIndex(new[] { "Naming" }, "UQ__Unit__EF1B1C3A358C331F")
                        .IsUnique();

                    b.ToTable("Unit", (string)null);
                });

            modelBuilder.Entity("PovarCRM.Models.Views.DishExpensiveView", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Naming")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<double?>("SummaryCost")
                        .HasColumnType("float")
                        .HasColumnName("SUMMARY_COST");

                    b.ToTable((string)null);

                    b.ToView("DishExpensiveView", (string)null);
                });

            modelBuilder.Entity("PovarCRM.Models.Dish", b =>
                {
                    b.HasOne("PovarCRM.Models.DishType", "DishType")
                        .WithMany("Dishes")
                        .HasForeignKey("DishTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Dish__DishTypeId__4E88ABD4");

                    b.Navigation("DishType");
                });

            modelBuilder.Entity("PovarCRM.Models.DishProduct", b =>
                {
                    b.HasOne("PovarCRM.Models.Unit", "Unit")
                        .WithMany("DishProducts")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__DishProdu__UnitI__5629CD9C");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("PovarCRM.Models.Item", b =>
                {
                    b.HasOne("PovarCRM.Models.Dish", "Dish")
                        .WithMany()
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Item__DishId__60A75C0F");

                    b.HasOne("PovarCRM.Models.OrderCheck", "OrderCheck")
                        .WithMany()
                        .HasForeignKey("OrderCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Item__OrderCheck__5FB337D6");

                    b.Navigation("Dish");

                    b.Navigation("OrderCheck");
                });

            modelBuilder.Entity("PovarCRM.Models.Recipe", b =>
                {
                    b.HasOne("PovarCRM.Models.Dish", "Dish")
                        .WithMany()
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Recipe__DishId__59063A47");

                    b.HasOne("PovarCRM.Models.DishProduct", "DishProduct")
                        .WithMany()
                        .HasForeignKey("DishProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Recipe__DishProd__59FA5E80");

                    b.Navigation("Dish");

                    b.Navigation("DishProduct");
                });

            modelBuilder.Entity("PovarCRM.Models.DishType", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("PovarCRM.Models.Unit", b =>
                {
                    b.Navigation("DishProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
